version: '3'
services:
  # ---------------------------
  # 前台
  # ---------------------------
  ui:
    image: ${BOOT_ADMIN_REGISTRY_URL}/${BOOT_ADMIN_UI_NAME}:latest
    build:
      context: .
    # volumes:
      # 挂载nginx的配置文件
      # - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: ${BOOT_ADMIN_UI_NAME}
    env_file: .env
    restart: always
    ports:
      - "80:80"

networks:
  net:
    driver: bridge

volumes:
  data:
    driver: local
