spring:
  liquibase:
    change-log: ${boot.admin.liquibase.change-log:classpath:liquibase/master.xml}
    enabled: true
    test-rollback-on-update: true
    contexts: ${spring.profiles.active}
  datasource:
    url: jdbc:mysql://${BOOT_ADMIN_DB_HOST:localhost}:${BOOT_ADMIN_DB_PORT:3306}/${BOOT_ADMIN_DB_DATABASE:boot-admin}?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${BOOT_ADMIN_DB_UNAME:root}
    password: ${BOOT_ADMIN_DB_PASSWORD:}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: true
        profile-enable: true
        exclusions: ${spring.boot.admin.context-path:/sba}/*
      filters: stat
      aop-patterns: com.boot.*.*.modules.*.service.*
      validation-query: SELECT 'X'
      filter:
        stat:
          merge-sql: true
      initial-size: 10
      min-idle: 5
      max-active: 200
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      remove-abandoned: false

mybatis-plus:
  typeEnumsPackage: com.boot.*.*.modules.*.api.enums;
  global-config:
    banner: false
  mapper-locations: classpath*:com/boot/*/*/modules/*/mapper/*.xml
  configuration:
    auto-mapping-behavior: FULL

boot.admin.mybatis.is-print-sql: ${BOOT_ADMIN_DB_IS-PRINT-SQL:false}