version: '3'
networks:
  net:
    driver: bridge
services:

  jjche-cloud-server-nacos-mysql:
    image: mysql:5.7.16
    container_name: ${JJCHE_DB_NACOS_HOST}
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      #数据库还原目录 可将需要还原的sql文件放在这里
      - ../jjche-cloud-nacos/src/main/resources/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${JJCHE_DB_NACOS_ROOT_PASSWORD}
      MYSQL_USER: ${JJCHE_DB_NACOS_UNAME}
      MYSQL_PASSWORD: ${JJCHE_DB_NACOS_PASSWORD}
      MYSQL_DATABASE: ${JJCHE_DB_NACOS_DATABASE}
      TZ: ${TZ}
    ports:
      - ${JJCHE_DB_NACOS_PORT_OUT}:${JJCHE_DB_NACOS_PORT}

  jjche-cloud-server-system-mysql:
    image: mysql:5.7.16
    container_name: ${JJCHE_DB_SYSTEM_HOST}
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${JJCHE_DB_SYSTEM_ROOT_PASSWORD}
      MYSQL_USER: ${JJCHE_DB_SYSTEM_UNAME}
      MYSQL_PASSWORD: ${JJCHE_DB_SYSTEM_PASSWORD}
      MYSQL_DATABASE: ${JJCHE_DB_SYSTEM_DATABASE}
      TZ: ${TZ}
    ports:
      - ${JJCHE_DB_SYSTEM_PORT_OUT}:${JJCHE_DB_SYSTEM_PORT}

  jjche-cloud-server-demo-student-mysql:
    image: mysql:5.7.16
    container_name: ${JJCHE_DB_DEMO_STUDENT_HOST}
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${JJCHE_DB_DEMO_STUDENT_ROOT_PASSWORD}
      MYSQL_USER: ${JJCHE_DB_DEMO_STUDENT_UNAME}
      MYSQL_PASSWORD: ${JJCHE_DB_DEMO_STUDENT_PASSWORD}
      MYSQL_DATABASE: ${JJCHE_DB_DEMO_STUDENT_DATABASE}
      TZ: ${TZ}
    ports:
      - ${JJCHE_DB_DEMO_STUDENT_PORT_OUT}:${JJCHE_DB_DEMO_STUDENT_PORT}

  jjche-cloud-server-redis:
    image: redis:6.2.0-alpine
    container_name: ${JJCHE_REDIS_HOST}
    restart: always
    command: --requirepass ${JJCHE_REDIS_PASSWORD}
    environment:
      TZ: ${TZ}
    ports:
      - ${JJCHE_REDIS_PORT_OUT}:${JJCHE_REDIS_PORT}

  jjche-boot-nacos:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_NACOS_HOST}:latest
    container_name: ${JJCHE_NACOS_HOST}
    env_file: ./.env
    ports:
      - ${JJCHE_NACOS_PORT}:${JJCHE_NACOS_PORT}
    depends_on:
      - jjche-cloud-server-nacos-mysql
    entrypoint: "sh /app/wait-for.sh jjche-cloud-server-nacos-mysql:3306 -- ${RUN_JAR}"
    environment:
      TZ: ${TZ}
      JJCHE_DB_HOST: ${JJCHE_DB_NACOS_HOST}
      JJCHE_DB_PORT: ${JJCHE_DB_NACOS_PORT}
      JJCHE_DB_UNAME: ${JJCHE_DB_NACOS_UNAME}
      JJCHE_DB_PASSWORD: ${JJCHE_DB_NACOS_PASSWORD}

  jjche-boot-monitor:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_MONITOR_NAME}:latest
    container_name: ${JJCHE_MONITOR_NAME}
    env_file: ./.env
    ports:
      - ${JJCHE_MONITOR_PORT}:${JJCHE_MONITOR_PORT}
    entrypoint: "sh /app/wait-for.sh jjche-boot-nacos:8848 -- ${RUN_JAR}"
    environment:
      TZ: ${TZ}

  jjche-boot-gateway:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_GATEWAY_NAME}:latest
    container_name: ${JJCHE_GATEWAY_NAME}
    env_file: ./.env
    ports:
      - ${JJCHE_GATEWAY_PORT}:${JJCHE_GATEWAY_PORT}
    entrypoint: "sh /app/wait-for.sh jjche-boot-nacos:8848 -- ${RUN_JAR}"
    environment:
      TZ: ${TZ}

  jjche-boot-system:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_SYSTEM_NAME}:latest
    container_name: ${JJCHE_SYSTEM_NAME}
    env_file: ./.env
    ports:
      - ${JJCHE_SYSTEM_PORT}:${JJCHE_SYSTEM_PORT}
    depends_on:
      - jjche-cloud-server-system-mysql
      - jjche-cloud-server-redis
    entrypoint: "sh /app/wait-for.sh jjche-boot-nacos:8848 -- sh /app/wait-for.sh jjche-cloud-server-system-mysql:3306 -- sh /app/wait-for.sh jjche-cloud-server-redis:6379 -- ${RUN_JAR}"
    environment:
      TZ: ${TZ}
      JJCHE_DB_HOST: ${JJCHE_DB_SYSTEM_HOST}
      JJCHE_DB_PORT: ${JJCHE_DB_SYSTEM_PORT}
      JJCHE_DB_UNAME: ${JJCHE_DB_SYSTEM_UNAME}
      JJCHE_DB_PASSWORD: ${JJCHE_DB_SYSTEM_PASSWORD}
      JJCHE_DB_DATABASE: ${JJCHE_DB_SYSTEM_DATABASE}

  jjche-boot-demo-provider:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_DEMO_PROVIDER_NAME}:latest
    container_name: ${JJCHE_DEMO_PROVIDER_NAME}
    env_file: ./.env
    ports:
      - ${JJCHE_DEMO_PROVIDER_PORT}:${JJCHE_DEMO_PROVIDER_PORT}
    depends_on:
      - jjche-cloud-server-demo-student-mysql
      - jjche-cloud-server-redis
    entrypoint: "sh /app/wait-for.sh jjche-boot-nacos:8848 -- sh /app/wait-for.sh jjche-cloud-server-demo-student-mysql:3306 -- sh /app/wait-for.sh jjche-cloud-server-redis:6379 -- ${RUN_JAR}"
    environment:
      TZ: ${TZ}
      JJCHE_DB_HOST: ${JJCHE_DB_DEMO_STUDENT_HOST}
      JJCHE_DB_PORT: ${JJCHE_DB_DEMO_STUDENT_PORT}
      JJCHE_DB_UNAME: ${JJCHE_DB_DEMO_STUDENT_UNAME}
      JJCHE_DB_PASSWORD: ${JJCHE_DB_DEMO_STUDENT_PASSWORD}
      JJCHE_DB_DATABASE: ${JJCHE_DB_DEMO_STUDENT_DATABASE}

  jjche-boot-demo-student:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_DEMO_STUDENT_NAME}:latest
    container_name: ${JJCHE_DEMO_STUDENT_NAME}
    env_file: ./.env
    ports:
      - ${JJCHE_DEMO_STUDENT_PORT}:${JJCHE_DEMO_STUDENT_PORT}
    depends_on:
      - jjche-cloud-server-demo-student-mysql
      - jjche-cloud-server-redis
    entrypoint: "sh /app/wait-for.sh jjche-boot-nacos:8848 -- sh /app/wait-for.sh jjche-cloud-server-demo-student-mysql:3306 -- sh /app/wait-for.sh jjche-cloud-server-redis:6379 -- ${RUN_JAR}"
    environment:
      TZ: ${TZ}
      JJCHE_DB_HOST: ${JJCHE_DB_DEMO_STUDENT_HOST}
      JJCHE_DB_PORT: ${JJCHE_DB_DEMO_STUDENT_PORT}
      JJCHE_DB_UNAME: ${JJCHE_DB_DEMO_STUDENT_UNAME}
      JJCHE_DB_PASSWORD: ${JJCHE_DB_DEMO_STUDENT_PASSWORD}
      JJCHE_DB_DATABASE: ${JJCHE_DB_DEMO_STUDENT_DATABASE}