version: '3'
networks:
  net:
    driver: bridge
services:

  jjche-cloud-server-nacos-mysql:
    image: ${MYSQL_VERSION}
    container_name: ${JJCHE_DB_NACOS_HOST}
    env_file: ./.env
    command: ${MYSQL_COMMAND}
    volumes:
      #数据库还原目录 可将需要还原的sql文件放在这里
      - ../jjche-cloud-nacos/src/main/resources/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${JJCHE_DB_NACOS_ROOT_PASSWORD}
      MYSQL_USER: ${JJCHE_DB_NACOS_UNAME}
      MYSQL_PASSWORD: ${JJCHE_DB_NACOS_PASSWORD}
      MYSQL_DATABASE: ${JJCHE_DB_NACOS_DATABASE}
      TZ: ${TZ}
    ports:
      - ${JJCHE_DB_NACOS_PORT_OUT}:${JJCHE_DB_NACOS_PORT}

  jjche-cloud-server-xxljob-mysql:
    image: ${MYSQL_VERSION}
    container_name: ${JJCHE_DB_XXLJOB_HOST}
    env_file: ./.env
    command: ${MYSQL_COMMAND}
    volumes:
      #数据库还原目录 可将需要还原的sql文件放在这里
      - ../jjche-cloud-xxljob/src/main/resources/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${JJCHE_DB_XXLJOB_ROOT_PASSWORD}
      MYSQL_USER: ${JJCHE_DB_XXLJOB_UNAME}
      MYSQL_PASSWORD: ${JJCHE_DB_XXLJOB_PASSWORD}
      MYSQL_DATABASE: ${JJCHE_DB_XXLJOB_DATABASE}
      TZ: ${TZ}
    ports:
      - ${JJCHE_DB_XXLJOB_PORT_OUT}:${JJCHE_DB_XXLJOB_PORT}

  jjche-cloud-server-system-mysql:
    image: ${MYSQL_VERSION}
    container_name: ${JJCHE_DB_SYSTEM_HOST}
    env_file: ./.env
    command: ${MYSQL_COMMAND}
    environment:
      MYSQL_ROOT_PASSWORD: ${JJCHE_DB_SYSTEM_ROOT_PASSWORD}
      MYSQL_USER: ${JJCHE_DB_SYSTEM_UNAME}
      MYSQL_PASSWORD: ${JJCHE_DB_SYSTEM_PASSWORD}
      MYSQL_DATABASE: ${JJCHE_DB_SYSTEM_DATABASE}
      TZ: ${TZ}
    ports:
      - ${JJCHE_DB_SYSTEM_PORT_OUT}:${JJCHE_DB_SYSTEM_PORT}

  jjche-cloud-server-demo-student-mysql:
    image: ${MYSQL_VERSION}
    container_name: ${JJCHE_DB_DEMO_STUDENT_HOST}
    env_file: ./.env
    command: ${MYSQL_COMMAND}
    environment:
      MYSQL_ROOT_PASSWORD: ${JJCHE_DB_DEMO_STUDENT_ROOT_PASSWORD}
      MYSQL_USER: ${JJCHE_DB_DEMO_STUDENT_UNAME}
      MYSQL_PASSWORD: ${JJCHE_DB_DEMO_STUDENT_PASSWORD}
      MYSQL_DATABASE: ${JJCHE_DB_DEMO_STUDENT_DATABASE}
      TZ: ${TZ}
    ports:
      - ${JJCHE_DB_DEMO_STUDENT_PORT_OUT}:${JJCHE_DB_DEMO_STUDENT_PORT}

  jjche-cloud-server-redis:
    image: redis:6.2.0-alpine
    container_name: ${JJCHE_REDIS_HOST}
    env_file: ./.env
    command: --requirepass ${JJCHE_REDIS_PASSWORD}
    environment:
      TZ: ${TZ}
    ports:
      - ${JJCHE_REDIS_PORT_OUT}:${JJCHE_REDIS_PORT}

  jjche-boot-nacos:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_NACOS_HOST}:latest
    container_name: ${JJCHE_NACOS_HOST}
    env_file: ./.env
    restart: "on-failure:3"
    ports:
      - ${JJCHE_NACOS_PORT}:${JJCHE_NACOS_PORT}
    depends_on:
      - jjche-cloud-server-nacos-mysql
    environment:
      TZ: ${TZ}
      JJCHE_DB_HOST: ${JJCHE_DB_NACOS_HOST}
      JJCHE_DB_PORT: ${JJCHE_DB_NACOS_PORT}
      JJCHE_DB_UNAME: ${JJCHE_DB_NACOS_UNAME}
      JJCHE_DB_PASSWORD: ${JJCHE_DB_NACOS_PASSWORD}

  jjche-boot-server-minio:
    image: quay.io/minio/minio:RELEASE.2023-02-10T18-48-39Z
    container_name: ${JJCHE_SERVER_MINIO_HOST}
    env_file: ./.env
    command: server /data/minio/
    environment:
      MINIO_ROOT_USER: ${JJCHE_SERVER_MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${JJCHE_SERVER_MINIO_SECRET_KEY}
    ports:
      - ${JJCHE_SERVER_MINIO_PORT_OUT}:${JJCHE_SERVER_MINIO_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  jjche-boot-xxljob:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_XXLJOB_HOST}:latest
    container_name: ${JJCHE_XXLJOB_HOST}
    env_file: ./.env
    restart: "on-failure:3"
    ports:
      - ${JJCHE_XXLJOB_PORT}:${JJCHE_XXLJOB_PORT}
    depends_on:
      - jjche-cloud-server-xxljob-mysql
    environment:
      TZ: ${TZ}
      JJCHE_DB_HOST: ${JJCHE_DB_XXLJOB_HOST}
      JJCHE_DB_PORT: ${JJCHE_DB_XXLJOB_PORT}
      JJCHE_DB_UNAME: ${JJCHE_DB_XXLJOB_UNAME}
      JJCHE_DB_PASSWORD: ${JJCHE_DB_XXLJOB_PASSWORD}

  jjche-boot-minio:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_MINIO_HOST}:latest
    container_name: ${JJCHE_MINIO_HOST}
    env_file: ./.env
    restart: "on-failure:3"
    ports:
      - ${JJCHE_MINIO_PORT}:${JJCHE_MINIO_PORT}
    depends_on:
      - jjche-boot-server-minio
    environment:
      TZ: ${TZ}
      JJCHE_MINIO_PORT: ${JJCHE_MINIO_PORT}
      JJCHE_SERVER_MINIO_HOST: http://${JJCHE_SERVER_MINIO_HOST}
      JJCHE_SERVER_MINIO_PORT: ${JJCHE_SERVER_MINIO_PORT}
      JJCHE_SERVER_MINIO_ACCESS_KEY: ${JJCHE_SERVER_MINIO_ACCESS_KEY}
      JJCHE_SERVER_MINIO_SECRET_KEY: ${JJCHE_SERVER_MINIO_SECRET_KEY}

  jjche-boot-monitor:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_MONITOR_NAME}:latest
    container_name: ${JJCHE_MONITOR_NAME}
    env_file: ./.env
    restart: "on-failure:3"
    ports:
      - ${JJCHE_MONITOR_PORT}:${JJCHE_MONITOR_PORT}
    environment:
      TZ: ${TZ}
    depends_on:
      - jjche-boot-nacos

  jjche-boot-gateway:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_GATEWAY_NAME}:latest
    container_name: ${JJCHE_GATEWAY_NAME}
    env_file: ./.env
    restart: "on-failure:3"
    ports:
      - ${JJCHE_GATEWAY_PORT}:${JJCHE_GATEWAY_PORT}
    environment:
      TZ: ${TZ}
    depends_on:
      - jjche-boot-nacos

  jjche-boot-system:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_SYSTEM_NAME}:latest
    container_name: ${JJCHE_SYSTEM_NAME}
    env_file: ./.env
    restart: "on-failure:3"
    ports:
      - ${JJCHE_SYSTEM_PORT}:${JJCHE_SYSTEM_PORT}
    depends_on:
      - jjche-cloud-server-system-mysql
      - jjche-cloud-server-redis
    environment:
      TZ: ${TZ}
      JJCHE_DB_HOST: ${JJCHE_DB_SYSTEM_HOST}
      JJCHE_DB_PORT: ${JJCHE_DB_SYSTEM_PORT}
      JJCHE_DB_UNAME: ${JJCHE_DB_SYSTEM_UNAME}
      JJCHE_DB_PASSWORD: ${JJCHE_DB_SYSTEM_PASSWORD}
      JJCHE_DB_DATABASE: ${JJCHE_DB_SYSTEM_DATABASE}

  jjche-boot-demo-provider:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_DEMO_PROVIDER_NAME}:latest
    container_name: ${JJCHE_DEMO_PROVIDER_NAME}
    env_file: ./.env
    restart: "on-failure:3"
    ports:
      - ${JJCHE_DEMO_PROVIDER_PORT}:${JJCHE_DEMO_PROVIDER_PORT}
    depends_on:
      - jjche-cloud-server-demo-student-mysql
      - jjche-cloud-server-redis
    environment:
      TZ: ${TZ}
      JJCHE_DB_HOST: ${JJCHE_DB_DEMO_STUDENT_HOST}
      JJCHE_DB_PORT: ${JJCHE_DB_DEMO_STUDENT_PORT}
      JJCHE_DB_UNAME: ${JJCHE_DB_DEMO_STUDENT_UNAME}
      JJCHE_DB_PASSWORD: ${JJCHE_DB_DEMO_STUDENT_PASSWORD}
      JJCHE_DB_DATABASE: ${JJCHE_DB_DEMO_STUDENT_DATABASE}

  jjche-boot-demo-student:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_DEMO_STUDENT_NAME}:latest
    container_name: ${JJCHE_DEMO_STUDENT_NAME}
    env_file: ./.env
    restart: "on-failure:3"
    ports:
      - ${JJCHE_DEMO_STUDENT_PORT}:${JJCHE_DEMO_STUDENT_PORT}
    depends_on:
      - jjche-cloud-server-demo-student-mysql
      - jjche-cloud-server-redis
    environment:
      TZ: ${TZ}
      JJCHE_DB_HOST: ${JJCHE_DB_DEMO_STUDENT_HOST}
      JJCHE_DB_PORT: ${JJCHE_DB_DEMO_STUDENT_PORT}
      JJCHE_DB_UNAME: ${JJCHE_DB_DEMO_STUDENT_UNAME}
      JJCHE_DB_PASSWORD: ${JJCHE_DB_DEMO_STUDENT_PASSWORD}
      JJCHE_DB_DATABASE: ${JJCHE_DB_DEMO_STUDENT_DATABASE}
