version: '3'
services:

  boot-admin-server-mysql:
    image: mysql:5.7.16
    container_name: ${BOOT_ADMIN_DB_HOST}
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    #    volumes:
    #      - ./volumes/${BOOT_ADMIN_DB_HOST}/data:/var/lib/mysql
    #      - ./volumes/${BOOT_ADMIN_DB_HOST}/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    #      #数据库还原目录 可将需要还原的sql文件放在这里
    #      - ./volumes/${BOOT_ADMIN_DB_HOST}/source:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${BOOT_ADMIN_DB_ROOT_PASSWORD}
      MYSQL_USER: ${BOOT_ADMIN_DB_UNAME}
      MYSQL_PASSWORD: ${BOOT_ADMIN_DB_PASSWORD}
      MYSQL_DATABASE: ${BOOT_ADMIN_DB_DATABASE}
      TZ: ${TZ}
    ports:
      - ${BOOT_ADMIN_DB_PORT_OUT}:${BOOT_ADMIN_DB_PORT}

  boot-admin-server-redis:
    image: redis:6.2.0-alpine
    container_name: ${BOOT_ADMIN_REDIS_HOST}
    restart: always
    command: --requirepass ${BOOT_ADMIN_REDIS_PASSWORD}
    #    volumes:
    #      - ./volumes/${BOOT_ADMIN_REDIS_HOST}/data:/data
    #      - ./volumes/${BOOT_ADMIN_REDIS_HOST}/conf/redis.conf:/usr/local/etc/redis/redis.conf
    #      - ./volumes/${BOOT_ADMIN_REDIS_HOST}/logs:/logs
    environment:
      TZ: ${TZ}
    ports:
      - ${BOOT_ADMIN_REDIS_PORT_OUT}:${BOOT_ADMIN_REDIS_PORT}

  boot-admin-web-demo:
    image: ${BOOT_ADMIN_REGISTRY_URL}/${BOOT_ADMIN_WEB_NAME}:latest
    container_name: ${BOOT_ADMIN_WEB_NAME}
#    restart: always
    env_file: ./.env
    ports:
      - ${BOOT_ADMIN_WEB_PORT}:${BOOT_ADMIN_WEB_PORT}
    depends_on:
      - boot-admin-server-mysql
      - boot-admin-server-redis
#    volumes:
#      - "./wait-for.sh:/wait-for.sh"
    entrypoint: "sh /wait-for.sh boot-admin-server-mysql:3306 -- sh /wait-for.sh boot-admin-server-redis:6379 -- ${RUN_JAR}"
    environment:
      TZ: ${TZ}

networks:
  net:
    driver: bridge