version: '3'
services:

  jjche-boot-server-mysql:
    image: mysql:5.7.16
    container_name: ${JJCHE_DB_HOST}
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    #    volumes:
    #      - ./volumes/${JJCHE_DB_HOST}/data:/var/lib/mysql
    #      - ./volumes/${JJCHE_DB_HOST}/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    #      #数据库还原目录 可将需要还原的sql文件放在这里
    #      - ./volumes/${JJCHE_DB_HOST}/source:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${JJCHE_DB_ROOT_PASSWORD}
      MYSQL_USER: ${JJCHE_DB_UNAME}
      MYSQL_PASSWORD: ${JJCHE_DB_PASSWORD}
      MYSQL_DATABASE: ${JJCHE_DB_DATABASE}
      TZ: ${TZ}
    ports:
      - ${JJCHE_DB_PORT_OUT}:${JJCHE_DB_PORT}

  jjche-boot-server-redis:
    image: redis:6.2.0-alpine
    container_name: ${JJCHE_REDIS_HOST}
    restart: always
    command: --requirepass ${JJCHE_REDIS_PASSWORD}
    #    volumes:
    #      - ./volumes/${JJCHE_REDIS_HOST}/data:/data
    #      - ./volumes/${JJCHE_REDIS_HOST}/conf/redis.conf:/usr/local/etc/redis/redis.conf
    #      - ./volumes/${JJCHE_REDIS_HOST}/logs:/logs
    environment:
      TZ: ${TZ}
    ports:
      - ${JJCHE_REDIS_PORT_OUT}:${JJCHE_REDIS_PORT}

  jjche-boot-demo:
    image: ${JJCHE_REGISTRY_URL}/${JJCHE_WEB_NAME}:latest
    container_name: ${JJCHE_WEB_NAME}
    #    restart: always
    env_file: ./.env
    ports:
      - ${JJCHE_WEB_PORT}:${JJCHE_WEB_PORT}
    depends_on:
      - jjche-boot-server-mysql
      - jjche-boot-server-redis
    entrypoint: "sh /app/wait-for.sh jjche-boot-server-mysql:3306 -- sh /app/wait-for.sh jjche-boot-server-redis:6379 -- ${RUN_JAR}"
    environment:
      TZ: ${TZ}

networks:
  net:
    driver: bridge
