spring:
  liquibase:
    change-log: ${jjche.liquibase.change-log:classpath:liquibase/master.xml}
    enabled: true
    test-rollback-on-update: true
    contexts: ${spring.profiles.active}
    default-schema: ${JJCHE_DB_DATABASE:jjche-boot}
  datasource:
    url: jdbc:mysql://${JJCHE_DB_HOST:localhost}:${JJCHE_DB_PORT:3306}/${spring.liquibase.default-schema}?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true
    username: ${JJCHE_DB_UNAME:root}
    password: ${JJCHE_DB_PASSWORD:}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: true
        profile-enable: true
        exclusions: ${spring.boot.admin.context-path:/sba}/*
      filters: stat
      aop-patterns: org.jjche.*.modules.*.service.*
      validation-query: SELECT 'X'
      filter:
        stat:
          # 开启监控sql
          enabled: true
          # 显示并标注慢sql 默认当超过3秒显示
          log-slow-sql: true
          slow-sql-millis: 3000
      initial-size: 10
      min-idle: 5
      max-active: 200
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      remove-abandoned: false

mybatis-plus:
  typeEnumsPackage: org.jjche.*.modules.*.api.enums;
  typeAliasesPackage: org.jjche.*.modules.*.domain;org.jjche.*.modules.*.api.vo;
  global-config:
    banner: false
  mapper-locations: classpath*:org/jjche/*/modules/*/mapper/*.xml
  configuration:
    auto-mapping-behavior: FULL

jjche.mybatis.is-print-sql: ${JJCHE_DB_IS_PRINT_SQL:false}