server:
  port: 8801
spring:
  application:
    name: jjche-cloud-gateway
  cloud:
    nacos:
      discovery:
        namespace: ${JJCHE_NACOS_NAMESPACE:}
        server-addr: ${JJCHE_NACOS_HOST:127.0.0.1}:${JJCHE_NACOS_PORT:8848}
      route:
        config:
          data-id: jjche-cloud-gateway-router
          group: DEFAULT_GROUP
          #自定义路由配置 yml nacos database
          data-type: nacos
    #Sentinel配置
    sentinel:
      web-context-unify: false
      transport:
        dashboard: localhost:8087
      # 懒加载Sentinel Dashboard菜单
      eager: false
    gateway:
      discovery:
        locator:
          enabled: true
      #如果启用nacos或者数据库配置请删除一下配置
      #      routes:
      #        - id: JJCHE-BOOT-DEMO
      #          uri: lb://jjche-boot-demo
      #          predicates:
      #            - Path=/api/**
      #        - id: JJCHE-CLOUD-SYSTEM
      #          uri: lb://jjche-cloud-system
      #          predicates:
      #            - Path=/api/sys/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: false
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      # 全局熔断降级配置
#      default-filters:
#        - name: Hystrix
#          args:
#            name: default
#            #转发地址
#            fallbackUri: 'forward:/fallback'
#        - name: Retry
#          args:
#            #重试次数，默认值是 3 次
#            retries: 3
#            #HTTP 的状态返回码
#            statuses: BAD_GATEWAY,BAD_REQUEST
#            #指定哪些方法的请求需要进行重试逻辑，默认值是 GET 方法
#            methods: GET,POST
# hystrix 信号量隔离，3秒后自动超时
hystrix:
  enabled: true
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000