knife4j:
  enable: true
  #  documents:
  #    -
  #      group: default
  #      name: 前端手册
  #      locations: classpath*:markdown/frontend/*
  #    -
  #      group: default
  #      name: 后端手册
  #      locations: classpath*:markdown/backend/*
  setting:
    enableSwaggerModels: false
    enableVersion: true
    enableReloadCacheParameter: true
    enableFooter: false
    enableDynamicParameter: true
    enableDocumentManage: true
    enableGroup: true
    enableOpenApi: false
jjche:
  swagger:
    filter-path: ${jjche.core.api.path.global-prefix}
    ignore-filter-path:
      - ${jjche.core.api.path.sys-prefix}.*
      - /error.*
    title: ${info.name:}
    version: ${info.version:}
    description: ${info.description:}
    encryption-enabled: ${jjche.filter.encryption.enabled:false}
    security-jwt:
      enabled: ${jjche.security.enabled:false}
      token-header: ${jjche.security.jwt.header}
      token-start-with: ${jjche.security.jwt.token-start-with}
