jjche:
  security:
    jwt:
      header: Authorization
      # 令牌前缀
      token-start-with: Bearer
      base64-secret: ${JJCHE_SECURITY_JWT_BASE64_SECRET:WW5NTU1oN09SYTZjbkR2Tm90N2p6Qm40U3BraUdPeGZ0cWtEU2RmQVVFWWl2bmpjMllwWDdZMGM3TXZnbUZYNW4yenp0aWV6UlNvRm85TUZ1WUwxc0ZpY1lJamdza2dodWx0RU5DZGd4TDFlZDJxbk1DSDlTU3JBYWxLRXZtbHU=}
      token-validity-in-milli-seconds: 7200000
      detect: 1800000
      online-key: "online-token:"
      code-key: "code:"

    login:
      # 登录缓存
      cache-enable: true
      #  是否限制单用户登录
      single: false
      #  验证码
      login-code:
        #  验证码类型配置 查看 SecurityLoginProperties 类
        code-type: spec
        #  登录图形验证码有效时间/毫秒
        expiration: 120000
        #  验证码高度
        width: 111
        #  验证码宽度
        height: 36
        # 内容长度
        length: 4
        # 字体名称，为空则使用默认字体
        font-name:
        # 字体大小
        font-size: 25
    url:
      exclude-default-urls:
        - /
        - ${spring.boot.admin.context-path:/sba}/**
        - /static/**
        - /*.ico
        - /*.html
        - /**/*.html
        - /**/*.css
        - /**/*.js
        - ${jjche.core.api.path.sys-prefix}/webSocket/**
        - /avatar/**
        - /file/**
        - /actuator/**
    #密码加密传输，前端公钥加密，后端私钥解密
    rsa:
      public_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDK4b3DKtM26QeA++8vElist/F3
        Nc1+cDnJwk1LJGLmssjzLTaSA2HGHyyQdGQz8J8+KUJDN0SMPUVyy8bTH5FzSfGv
        KbVG4/wg3CWDqx09uP4KL8TBBnrcnjWdnYmftJGp3xDbCoSxNzCnxhvn/G/0LIYl
        Gt0lyhOKnLjyPFoQsQIDAQAB
      private_key: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAMrhvcMq0zbpB4D7
        7y8SWKy38Xc1zX5wOcnCTUskYuayyPMtNpIDYcYfLJB0ZDPwnz4pQkM3RIw9RXLL
        xtMfkXNJ8a8ptUbj/CDcJYOrHT24/govxMEGetyeNZ2diZ+0kanfENsKhLE3MKfG
        G+f8b/QshiUa3SXKE4qcuPI8WhCxAgMBAAECgYEAx7r7PVNAwpMhLwtXSokOQWOJ
        VWnjVzGWwpkFzQ8SSroB+N0vFwo7THfOQJxFNZkSvHiT4mZblpCPeVdB8wDmB84x
        MvPO2DUdkhJnuw8h9ktSc8yhRhPy421FEkhZGUWn0Njnq6ioMyUSUZNqyisMAY5F
        x6gYrJQM/YupeYk2Tq0CQQD6bEkolrIjYAHLgEXkjSnP5SzjA22t1QP4p44mJeYB
        pSQYRjGj61IZhbbaW3TbqmmYpagxYOmLkluaoTM2vc2LAkEAz2ZpxA4ypu5Uds5J
        XsKviAqMTefSktse6YmiVGhfiwLgEsoObqJvUcRznjse3zbub0vUajpa2VzP67C6
        kj4aMwJBAN9MC3gb18BfbXpOaQRBM5VjX0EV34jvttjUX5Z4mL3CyYqznLPzs4N6
        je/rOSperEYnAPD234lK+k/Jiec4G70CQQCoGtqfjuJ/a64KninaJPMh0Wrnun9z
        iSgFIwnwYKkQg8Qbdqs8AW05WYJdPo5HXr7kdxI1CBebFx9wak7POocBAkB3+1kF
        iWXgxZxveijZItNXvHMe8wF+eXpsasJYrjWv3if6A9BvdWRLqqS1T1Zy2h8z+d4F
        GH4sygdMAPRyuXMl